### ISSUE TITLE
Parsing error when running gatsby

### ISSUE THREAD

**Issue by littlefengers** [contentstack/gatsby-source-contentstack#184]
Hello, I haven't made any changes to my gatsby build in the last month and just recently, I am unable to spin up gatsby.

I am getting this

```
Encountered an error parsing the provided GraphQL type definitions:
Syntax Error: Invalid number, expected digit but got: "v".

> 1 | type Contentstack_component_doc-v3 implements Node @infer { title: String! }
    |                                 ^


not finished createSchemaCustomization - 0.08

```

Was there a recent change made to contentstack that could cause this?

**Comment by abhishek305** [comment]
Hi @littlefengers ,
We haven't made any changes to the source plugin in a while and since when you are receiving this error?
Could you share the gatsby-source-contentstack version?

**Comment by littlefengers** [comment]
> Hi @littlefengers , We haven't made any changes to the source plugin in a while and since when you are receiving this error? Could you share the gatsby-source-contentstack version?

I'm on 4.0.4, I meant was there anything that changed on the contentstack side (not the plugin) that is causing this error?

**Comment by abhishek305** [comment]
> > Hi @littlefengers , We haven't made any changes to the source plugin in a while and since when you are receiving this error? Could you share the gatsby-source-contentstack version?
> 
> I'm on 4.0.4, I meant was there anything that changed on the contentstack side (not the plugin) that is causing this error?

Hi @littlefengers,
There have been no changes in the Contentstack's API as well,

As per my findings, there seems to be some issue with the content type "**component_doc-v3**"

content-type UID should never consist of **hyphen** when creating a content type from Contentstack UI special characters like "-","@" etc are not accepted in the content type UID 

Example:
Content type name: "**Testing header**" and its UID should be: "**testing_header**" the UID would only consists of "_" as special character not hyphen

So while generating graphql schema for the content type in our source plugin graphql doesn't accepts special character like "-"  that is why it is pointing to the last char "v".

Refer to these issues not specific to gatsby but for graphql: 

https://github.com/aws-amplify/amplify-cli/issues/5206#issuecomment-683989068 
https://github.com/aws-amplify/amplify-cli/issues/5206#issuecomment-685015559

Could you try creating a content type with UID that would only consist of "_" and not "-" as updating that content type UID is not possible also when creating a content type Contentstack handles special characters like "-" which would automatically convert it to a "_".Make you while creating content types & its UID's "_" is used instead of any special chars even through API.

I cannot see this as an issue from the plugin and we haven't made any changes to the schema generation method in a while.

Let me know if this helps

Thanks !!

**Comment by littlefengers** [comment]
Thank you for your help! That worked. Very odd that I was able to use "-" in the UID all this time until recently.
